### ISSUE TITLE
Clarify inclusiveness of min/max tier boundaries

### ISSUE THREAD

**Issue by ragnard** [PriceComparisonStandardsGroup/AddOns#3]
Currently, there is no clear specification of the inclusiveness of the `Min` and `Max` attributes of a `Tier`.

We propose that `Min` is inclusive and `Max` exclusive, and have submitted https://github.com/PriceComparisonStandardsGroup/AddOns/pull/2 implementing that change through clearer wording in documentation.

**Comment by wardpatrick** [comment]
Makes perfect sense from our point of view. Unless anyone thinks otherwise I will make that change

**Comment by wardpatrick** [comment]
@MattCollinge, @apstewart You happy for me to merge in the changes

**Comment by wardpatrick** [comment]
@ragnard would you like to check the source and close if happy

**Comment by ragnard** [comment]
Looks good, thanks.
