### ISSUE TITLE
missing finance calculation examples

### ISSUE THREAD

**Issue by davie** [PriceComparisonStandardsGroup/AddOns#4]
At the meeting last week it was mentioned that there was a spreadsheet with the calculations & examples - could someone add these?

**Comment by wardpatrick** [comment]
Dave Fox has asked @StephenCollis to look this over, so it is happening.  

[InstalmentCalculator.xlsx](https://github.com/PriceComparisonStandardsGroup/AddOns/files/311963/InstalmentCalculator.xlsx)

**Comment by StephenCollis** [comment]
Please find the initial draft of the installment calculator pseudo code. It may benefit from additional commenting. This code may be executed on the [.net fiddle sandbox](https://dotnetfiddle.net/)
[InstallmentCalculator.cs.txt](https://github.com/PriceComparisonStandardsGroup/AddOns/files/312339/InstallmentCalculator.cs.txt)

**Comment by wardpatrick** [comment]
Take it SetupFee is the 'The Sum of all Fees that cannot be added to the loan' and LoanSetupFee 'Sum of all Fees that are added to the loan'

**Comment by StephenCollis** [comment]
The "Setup fee" is the broker fee added to the premium for the policy setup
regardless of whether the policy if financed or not, the "LoanSetupFee" is
an optional additional fee that the broker/Insurer may charge for the
privilege of setting up the finance.

Thinking about it I suspect that the "Setup Fee" is noise to an aggregator
as it would already have been included in the price returned.

_Stephen Collis_

IT Director
Tel   01473 542001
Mob 07748 633867

**Comment by wardpatrick** [comment]
@StephenCollis, @apstewart can you take a look at some queries I have added to the code snippet. Theme focuses around the fact **fees** and **deposits** could be denoted as a percentage amount and/or a fixed amount. @apstewart covered some scenarios, that is why we have an AmountType enum. Also would be useful to explicitly bind the public props in the pseudocode to the schema properties so we 100% clear on what is getting passed in.   

[ProgramQuestions.cs.txt](https://github.com/PriceComparisonStandardsGroup/AddOns/files/313617/ProgramQuestions.cs.txt)

**Comment by DaveFoxOpenGI** [comment]
The **setup fee** is **NOT** a fee regardless of whether finance is available or not. It is a fee for taking out finance but the provider wants the fee paid up front. 
The **finance fee** is a fee for taking out finance but is spread out over the term of the loan (and as such incurs interest charges also). 
Other fees that are regardless of finance are already included in the main insurance premium.

**Comment by wardpatrick** [comment]
So in the schema we denote a SetupFee, but we don't permit FinanceFee, so @DaveFoxOpenGI you suggest we add this. 

In the Pseudo code we have LoanSetupFees and SetupFees. So **LoanSetupFees (Pseudo code) =  SetupFee (schema)**, and **SetupFee (Pseudo code) = FinanceFee (schema)**.

So to remedy this we need to ensure that the Fees are clearly typed, SetupFee must not be added to the loan, AddToLoan="false".   FinanceFee AddToLoan="true"

@apstewart, @StephenCollis  do you agree with this?

**Comment by StephenCollis** [comment]
Sorry my miss-understanding I will make the corrections to the code. and
make sure the variables names in the sudo code are in line with the schema,
about to go into another meeting so give me a couple of hours.

_Stephen Collis_

IT Director
Tel   01473 542001
Mob 07748 633867

**Comment by wardpatrick** [comment]
Gents, do we need to change the schema like this?

``` xml
<c:Tier Min="0.00" Plan="Standard" Max="0.00">
        <c:Finance Cap="0.00" Term="1" Instalments="2"/>
        <c:Deposit Min="0.00" AmountType="Percentage">0.00</c:Deposit>
        <c:Interest Percentage="0.00" minimumAmount="0.00"/>
        <c:Charges>
            <c:Charge xsi:type="c:SetupFee">
                <c:Amount AmountType="Percentage">0.00</c:Amount>
            </c:Charge>
            <c:Charge xsi:type="c:FinanceFee">
                <c:Amount AmountType="Percentage">0.00</c:Amount>
            </c:Charge>
        </c:Charges>
    </c:Tier>
```

**Comment by DaveFoxOpenGI** [comment]
Yes, the above looks good to me.

**Comment by wardpatrick** [comment]
@StephenCollis, @apstewart can you work with that if we change the charges section?

**Comment by apstewart** [comment]
I believe the name of the charges should be at the discretion of the providers.  In the schema currently we have an attribute 'addToLoan' on the charge element, this attribute is used to identify if a charge is part of the initial payment or is included in interest calculations.

**Comment by wardpatrick** [comment]
@apstewart way means that we would still need to change the Charge name to an xs:token, currently it is restricted to an enum.

That works as all @StephenCollis need to do is to class any addToLoan fees as Finance fees, and likewise any non-addToLoan as setup fees as defined by @DaveFoxOpenGI , but understand we may need to be a bit more verbose with the terminology. instead of addToLoan we could denote a FeeType as  Setup or Finance, of just stick with the boolean, what say you Gents @StephenCollis @DaveFoxOpenGI             

e.g.

``` xml
    <c:Tier Min="0.00" Plan="Standard" Max="0.00">
        <c:Finance Cap="0.00" Term="1" Instalments="2"/>
        <c:Deposit Min="0.00" AmountType="Percentage">0.00</c:Deposit>
        <c:Interest Percentage="0.00" minimumAmount="0.00"/>
        <c:Charges>
            <c:Charge FeeType="SetUp" Name="Protection Racket Payment">
                <c:Amount AmountType="Percentage">0.00</c:Amount>
            </c:Charge>
                        <c:Charge FeeType="Finance" Name="Paperwork Fee">
                <c:Amount AmountType="Percentage">0.00</c:Amount>
            </c:Charge>
        </c:Charges>
    </c:Tier>

```

**Comment by apstewart** [comment]
So we have three options, two from @wardpatrick and this one.

``` xml
<c:Tier Min="0.00" Plan="Standard" Max="0.00">
    <c:Finance Cap="0.00" Term="1" Instalments="2"/>
    <c:Deposit Min="0.00" AmountType="Percentage">0.00</c:Deposit>
    <c:Interest Percentage="0.00" minimumAmount="0.00"/>
    <c:Charges>
        <c:Charge Name="Protection Racket Payment" AddToLoan="False">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
        <c:Charge Name="Paperwork Fee" AddToLoan="True">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
    </c:Charges>
</c:Tier>
```

**Comment by wardpatrick** [comment]
I agree we need to _at least_ drop the restriction on Charge Name but after that not fussy on the chosen option as we can work with all of them. 

@apstewart take it you vouch for option 3 i.e.

``` xml
  <c:Charge Name="Protection Racket Payment" AddToLoan="False">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
```

**Comment by DaveFoxOpenGI** [comment]
After discussion with Stephen Collis we'd like to suggest the charges are defined thus - due to there being potentially three points a Charge (due to paying by instalments) might be added during the calculation.
Also if we need more charges to be applied at different calculation points this is extensible by adding another 'Type'.
- AppliedToPremium -  Amount of extra fee due to paying by instalments that is added to the total premium before instalments and deposit are calculated
- AppliedToDeposit - Charge due to paying by instalments that should be paid for up front in the deposit
- AppliedToLoan - Charge due to paying by instalments that should be paid spread over the term of the loan. i.e. added purely to the loan amount to be 'financed' 

Also that only one Charge node should be sent per Type and a Type can only have one Amount node.
E.g.

``` xml
<c:Tier Min="0.00" Plan="Standard" Max="0.00">
    <c:Finance Cap="0.00" Term="1" Instalments="2"/>
    <c:Deposit Min="0.00" AmountType="Percentage">0.00</c:Deposit>
    <c:Interest Percentage="0.00" minimumAmount="0.00"/>
    <c:Charges>
        <c:Charge xsi:type="c:AppliedToDeposit">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
        <c:Charge xsi:type="c:AppliedToLoan">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
        <c:Charge xsi:type="c:AppliedToPremium">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
    </c:Charges>
</c:Tier>
```

**Comment by wardpatrick** [comment]
This would keep all parties happy, Name being optional free text (xs:token). Not relevant for calculation logic but good for audit trail. @apstewart you happy with this?

``` xml
<c:Tier Min="0.00" Plan="Standard" Max="0.00">
    <c:Finance Cap="0.00" Term="1" Instalments="2"/>
    <c:Deposit Min="0.00" AmountType="Percentage">0.00</c:Deposit>
    <c:Interest Percentage="0.00" minimumAmount="0.00"/>
    <c:Charges>
        <c:Charge xsi:type="c:AppliedToDeposit" Name="Protection Racket Payment">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
        <c:Charge xsi:type="c:AppliedToLoan" Name="Paperwork Fee">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
        <c:Charge xsi:type="c:AppliedToPremium" Name="Stealth Tax">
            <c:Amount AmountType="Percentage">0.00</c:Amount>
        </c:Charge>
    </c:Charges>
</c:Tier> 
```

**Comment by apstewart** [comment]
That works for me, it makes the intent explicit.  I'm not sure the name works in this context though as there might be multiple charges combined.  I expect in most cases it will be a single charge, but there is always one...

**Comment by wardpatrick** [comment]
OK, give me five an will update schema accordingly

**Comment by wardpatrick** [comment]
Right then, schema now validates the following, and only allows one charge per charge type.  

``` xml
<c:Tier Min="0.00" Plan="Standard" Max="0.00">
        <c:Finance Cap="0.00" Term="1" Instalments="2"/>
        <c:Deposit Min="0.00" AmountType="Percentage">0.00</c:Deposit>
        <c:Interest Percentage="0.00" minimumAmount="0.00"/>
        <c:Charges>
            <c:Charge xsi:type="c:AppliedToLoan" Name="Setup Fee">
                <c:Amount AmountType="Percentage">0.00</c:Amount>
            </c:Charge>
            <c:Charge xsi:type="c:AppliedToDeposit" Name="Peanuts Fee">
                <c:Amount AmountType="Percentage">0.00</c:Amount>
            </c:Charge>
            <c:Charge xsi:type="c:AppliedToPremium">
                <c:Amount AmountType="Percentage">0.00</c:Amount>
            </c:Charge>
        </c:Charges>
    </c:Tier>
```

Once  @StephenCollis provides updated Pseudo we should be in a position to close this issue.

**Comment by StephenCollis** [comment]
Pleased find attached revised sample code
[InstallmentCalculator.cs.txt](https://github.com/PriceComparisonStandardsGroup/AddOns/files/314154/InstallmentCalculator.cs.txt)

**Comment by wardpatrick** [comment]
Are we not missing this in the Pseudo code? i.e. the min interest check.  

``` C
            decimal minInterestAmount = 5m; 

            decimal interestAmount = loanAmount*NetInterestRate;

            if minInterestAmount < interestAmount
            {
               interestAmount = minInterestAmount;
            }

            decimal installmentAmount = (loanAmount + interestAmount)/NoOfInstallments;
```

**Comment by StephenCollis** [comment]
I have now included this with the MAX function
decimal interestAmount = Math.Max(MinInterestAmount,loanAmount \* NetInterestRate);
[InstallmentCalculator.cs.txt](https://github.com/PriceComparisonStandardsGroup/AddOns/files/314302/InstallmentCalculator.cs.txt)

**Comment by StephenCollis** [comment]
Are we happy to close this now, I don't think I have permission to upload the pseudo code file into the repository?

**Comment by apstewart** [comment]
I'll convert to markdown and add to the repo.

**Comment by wardpatrick** [comment]
We need top make sure we include this on this level plan, that also had a min interest check

**Comment by StephenCollis** [comment]
It can be added to the level plan but I don't think it is needed as this
can be easily covered by the MinLoanAmount.

_Stephen Collis_

IT Director
Tel   01473 542001
Mob 07748 633867

**Comment by apstewart** [comment]
I've submitted a pull request with the change to include the min interest check. 

The Min interest check will still be needed in cases where a low `MinLoanAmount` exists, I don't see the two things as being exclusive.  

If everyone is happy I will merge the change and close this issue.

**Comment by StephenCollis** [comment]
Yes I do see your point and you are correct, I am happy with the change.

**Comment by wardpatrick** [comment]
Look good to me, happy for @apstewart to merge and close
